# Generated by Django 4.2.11 on 2025-05-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_admin_dashboard', 'Can view admin dashboard'), ('can_manage_courses', 'Can manage courses'), ('can_take_quizzes', 'Can take quizzes')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], max_length=10),
        ),
    ]
