# Generated by Django 4.2.11 on 2025-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_take_quizzes', 'Can take quizzes')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee')], default='Employee', max_length=10),
        ),
    ]
