# Generated by Django 4.2.11 on 2025-05-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_option_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
