# Generated by Django 4.2.11 on 2025-05-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
        ('questions', '0004_materialprogress_alter_employeeprogress_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(default='multiple_choice', max_length=50),
        ),
    ]
