# Generated by Django 4.2.11 on 2025-05-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_question_option_a_remove_question_option_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprogress',
            name='modified_at',
        ),
    ]
