# Generated by Django 4.2.11 on 2025-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_employeeprogress_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Enter the YouTube video URL', max_length=255, null=True),
        ),
    ]
