# Generated by Django 4.2.11 on 2025-05-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_quizattempt_questionattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
